### ISSUE TITLE
Link for cython-hidapi is broken

### ISSUE THREAD

**Issue by rpanai** [K4CZP3R/hyperx-keyboard-rgb#1]
Hi. As per title you should change your link in README.md for
```
[https://github.com/trezor/cython-hidapi](https://github.com/trezor/cython-hidapi)
```

btw is this supposed to be used to change rgb colors in hyperx keyboard? Does it work from linux too?

**Comment by kacper-serewis** [comment]
Yup, it can change every key color. If cython hidapi is compatible with linux then it should work. Thanks!
