### ISSUE TITLE
self.hid.open_path(self.path) produces OSError: open failed 

### ISSUE THREAD

**Issue by VietTralala** [K4CZP3R/hyperx-keyboard-rgb#2]
Hi, I wanted to test your code on the HyperX Alloy Elite RGB.
Via the command `cat /proc/bus/input/devices` I could find the pid (0x0951) and the vid (0x16be) for my keyboard. The function `KspHidHelper.get_interface_path_for_pidvid()` returns paths for interface numbers 0,1,2.
However the constructor of  the class `KspHid` fails to open the returned path on line 8. Do you know why this is the case?

**Comment by kacper-serewis** [comment]
I've not tested it on Linux. Try to use another interface, maybe interface no.3 is no.2 on linux.

**Comment by michalfilippi** [comment]
Hi. Did you solve the issue? I have HyperX Alloy Origins Core keyboard and I see the same Error message on Mac OS. I changed the the `pid` and `vid` accordingly. Surprisingly, I have 7 device entries in `hid.enumerate()` corresponding to the keyboard, all of them fail to open with the error message mentioned above. 
Does the script require some special permissions?

**Comment by kacper-serewis** [comment]
This issue is almost 2 years old, but this is fixed now.
