### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by BeyCoder** [K4CZP3R/hyperx-keyboard-rgb#6]
Traceback (most recent call last):
  File "C:\Users\Beybut\Desktop\rgb\examples\example.py", line 2, in <module>
    from hyperx_keyboard_rgb.keyboard import KeyboardHelper, Keyboard
  File "C:\Users\Beybut\Desktop\rgb\hyperx_keyboard_rgb\keyboard.py", line 11, in <module>
    from hyperx_keyboard_rgb.helpers.ksp_hid_helper import KspHidHelper
  File "C:\Users\Beybut\Desktop\rgb\hyperx_keyboard_rgb\helpers\ksp_hid_helper.py", line 1, in <module>
    import hid
  File "C:\Users\Beybut\Desktop\rgb\venv\lib\site-packages\hid\__init__.py", line 30, in <module>
    raise ImportError(error)
ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll

**Comment by kacper-serewis** [comment]
Looks like hidapi is not installed, can you try to install it manually? `pip install hidapi`

**Comment by BeyCoder** [comment]
> Looks like hidapi is not installed, can you try to install it manually? `pip install hidapi`

yes

Requirement already satisfied: hidapi in c:\users\beybut\desktop\rgb\venv\src\hidapi (0.11.2)
Requirement already satisfied: setuptools>=19.0 in c:\users\beybut\desktop\rgb\venv\lib\site-packages (from hidapi) (60.2.0)

**Comment by kacper-serewis** [comment]
https://python-elgato-streamdeck.readthedocs.io/en/stable/pages/backend_libusb_hidapi.html#windows

**Comment by kacper-serewis** [comment]
@BeyCoder is your issue solved?

**Comment by BeyCoder** [comment]
@K4CZP3R i will try today
